[package]
name = "rustpython-compiler"
description = "A usability wrapper around rustpython-parser and rustpython-compiler-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
rustpython-codegen = { workspace = true }
rustpython-compiler-core = { workspace = true }
ruff_python_parser = { workspace = true }
ruff_python_ast = { workspace = true }
ruff_source_file = { workspace = true }
ruff_text_size = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(not(target_abi = "polyasm"))'.dependencies]
ruff_python_ast = { workspace = true, features = ["std"] }
ruff_python_parser = { workspace = true, features = ["std"] }
ruff_source_file = { workspace = true, features = ["std"] }
ruff_text_size = { workspace = true, features = ["std"] }
rustpython-codegen = { workspace = true, features = ["std"] }

[target.'cfg(target_abi = "polyasm")'.dependencies]
rustpython-std = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
